repos:
  # Use local/system hooks to call the installed tools in the active
  # Python environment. This avoids pre-commit attempting to clone/fetch
  # remote repositories (which can fail in air-gapped environments).
  - repo: local
    hooks:
      - id: black
        name: black (system)
        entry: black
        language: system
        types: [python]
        args: ["--fast"]

      - id: isort
        name: isort (system)
        entry: isort
        language: system
        types: [python]

      - id: ruff
        name: ruff (system)
        entry: ruff
        language: system
        types: [python]
        args: ["--fix"]
