repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/charliermarsh/ruff
    # Temporarily pin to main to avoid missing tag ('0.1.0') during pre-commit init.
    # Recommendation: replace with a stable release tag (e.g. 'v0.1.58') when ready.
    rev: main
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.13.0
    hooks:
      - id: isort
