repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/charliermarsh/ruff
    # Pin to a known stable release tag to avoid missing/tag checkout errors during
    # pre-commit initialization. If this tag becomes outdated, update to a
    # newer stable ruff release (for example: 'v0.1.58').
    rev: v0.1.58
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.13.0
    hooks:
      - id: isort
