version: '3.8'
services:
  redis:
    image: redis:7
    ports:
      - '6379:6379'

  web:
    build: .
    command: echo "Run your Django app here"
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A backend.celery_app.celery worker --loglevel=info
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
